# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('btime', models.DateTimeField(blank=True, null=True)),
                ('from_page', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_browse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('ctime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('ftime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('otime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('ptime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'data_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('content', models.CharField(max_length=50)),
                ('stime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('rpid', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'product_recommend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('spid', models.IntegerField()),
                ('similarity', models.FloatField()),
            ],
            options={
                'db_table': 'product_similarity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'user_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'user_recommend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRecommendBak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'user_recommend_bak',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('suid', models.IntegerField()),
                ('similarity', models.FloatField()),
            ],
            options={
                'db_table': 'user_similarity',
                'managed': False,
            },
        ),
    ]
