# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160804_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrecommend',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='userrecommend',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.DataProduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='dataproduct',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userrecommend',
            table=None,
        ),
    ]
